import pylhe
import skhep_testdata

from lheutils.cli.lhefilter import filter_lhe_file


def test_filter_lhe_file_preserves_initrwgt_header(tmp_path):
    output_file = tmp_path / "filtered_weighted.lhe"

    filter_lhe_file(
        input_file=skhep_testdata.data_path("pylhe-testlhef3.lhe"),
        rwgt=False,
        weights=True,
        output_file=str(output_file),
        max_events=1,
    )

    filtered = pylhe.LHEFile.fromfile(output_file)
    assert filtered.header is not None
    assert len(filtered.header.initrwgt.entries) == 1
    entry = filtered.header.initrwgt.entries[0]
    assert isinstance(entry, pylhe.LHEInitRWGTWeightGroup)
    assert entry.attributes["type"] == "scale_variation"
    assert len(entry.weights) == 9


def test_filter_lhe_file_preserves_comment_and_root_attributes(tmp_path):
    input_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")
    output_file = tmp_path / "filtered_comment.lhe"

    filter_lhe_file(
        input_file=input_file,
        rwgt=True,
        weights=False,
        output_file=str(output_file),
        max_events=1,
    )

    output_text = output_file.read_text()
    assert output_text.startswith('<LesHouchesEvents version="1.0">')
    assert (
        "<!-- File generated by GiBUU. For documentation see "
        "https://gibuu.hepforge.org/trac/wiki/LesHouches -->"
    ) in output_text
