import pylhe
import skhep_testdata

from lheutils.cli.lhemerge import merge_lhe_files


def test_merge_lhe_files_preserves_initrwgt_header(tmp_path):
    output_file = tmp_path / "merged_weighted.lhe"

    code, message = merge_lhe_files(
        [
            "references/files/pylhe-testlhef3.lhe",
            "references/files/pylhe-testlhef3.lhe",
        ],
        output_file=str(output_file),
        rwgt=False,
        weights=True,
    )

    assert code == 0
    assert "Merged 2 files into" in message

    merged = pylhe.LHEFile.fromfile(output_file)
    assert merged.header is not None
    assert len(merged.header.initrwgt.entries) == 1
    entry = merged.header.initrwgt.entries[0]
    assert isinstance(entry, pylhe.LHEInitRWGTWeightGroup)
    assert entry.attributes["type"] == "scale_variation"
    assert len(entry.weights) == 9


def test_merge_lhe_files_preserves_comment_and_root_attributes_on_stdout(capsys):
    input_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")

    code, message = merge_lhe_files(
        [input_file, input_file],
        output_file=None,
        rwgt=True,
        weights=False,
    )

    assert code == 0
    assert "Merged 2 files to stdout" in message

    output = capsys.readouterr().out
    assert output.startswith('<LesHouchesEvents version="1.0">')
    assert (
        "<!-- File generated by GiBUU. For documentation see "
        "https://gibuu.hepforge.org/trac/wiki/LesHouches -->"
    ) in output
