from pathlib import Path

import pylhe
import skhep_testdata

from lheutils.cli.lhemerge import merge_lhe_files


def test_merge_lhe_files_preserves_initrwgt_header(tmp_path):
    output_file = tmp_path / "merged_weighted.lhe"

    code, message = merge_lhe_files(
        [
            skhep_testdata.data_path("pylhe-testlhef3.lhe"),
            skhep_testdata.data_path("pylhe-testlhef3.lhe"),
        ],
        output_file=str(output_file),
        weight_format=pylhe.LHEWeightFormat.WEIGHTS,
    )

    assert code == 0
    assert "Merged 2 files into" in message

    merged = pylhe.LHEFile.fromfile(output_file)
    assert merged.header is not None
    assert len(merged.header.initrwgt.entries) == 1
    entry = merged.header.initrwgt.entries[0]
    assert isinstance(entry, pylhe.LHEInitRWGTWeightGroup)
    assert entry.attributes["type"] == "scale_variation"
    assert len(entry.weights) == 9


def test_merge_lhe_files_preserves_comment_and_root_attributes_on_stdout(capsys):
    input_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")

    code, message = merge_lhe_files(
        [input_file, input_file],
        output_file=None,
        weight_format=pylhe.LHEWeightFormat.RWGT,
    )

    assert code == 0
    assert "Merged 2 files to stdout" in message

    output = capsys.readouterr().out
    assert output.startswith('<LesHouchesEvents version="1.0">')
    assert (
        "<!-- File generated by GiBUU. For documentation see "
        "https://gibuu.hepforge.org/trac/wiki/LesHouches -->"
    ) in output


def test_merge_lhe_files_rejects_different_initrwgt(tmp_path):
    original = skhep_testdata.data_path("pylhe-testlhef3.lhe")
    modified = tmp_path / "modified_weights.lhe"
    modified.write_text(
        Path(original)
        .read_text()
        .replace(
            "muR=0.10000E+01 muF=0.20000E+01",
            "changed initrwgt weight",
            1,
        )
    )

    code, message = merge_lhe_files(
        [original, str(modified)],
        output_file=None,
        weight_format=pylhe.LHEWeightFormat.WEIGHTS,
    )

    assert code == 1
    assert "different initrwgt header sections" in message
