import pylhe
import skhep_testdata

from lheutils.cli.lhesplit import split_lhe_file


def test_split_lhe_file_preserves_initrwgt_header(tmp_path):
    output_base = tmp_path / "split_weighted.lhe"

    code, message = split_lhe_file(
        "references/files/pylhe-testlhef3.lhe",
        str(output_base),
        num_events=1,
        rwgt=False,
        weights=True,
    )

    assert code == 0
    assert "Split events into" in message

    split_file = pylhe.LHEFile.fromfile(tmp_path / "split_weighted_1.lhe")
    assert split_file.header is not None
    assert len(split_file.header.initrwgt.entries) == 1
    entry = split_file.header.initrwgt.entries[0]
    assert isinstance(entry, pylhe.LHEInitRWGTWeightGroup)
    assert entry.attributes["type"] == "scale_variation"
    assert len(entry.weights) == 9


def test_split_lhe_file_preserves_comment_and_root_attributes(tmp_path):
    input_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")
    output_base = tmp_path / "split_comment.lhe"

    code, message = split_lhe_file(
        input_file,
        str(output_base),
        num_events=1,
        rwgt=True,
        weights=False,
    )

    assert code == 0
    assert "Split events into" in message

    output_text = (tmp_path / "split_comment_1.lhe").read_text()
    assert output_text.startswith('<LesHouchesEvents version="1.0">')
    assert (
        "<!-- File generated by GiBUU. For documentation see "
        "https://gibuu.hepforge.org/trac/wiki/LesHouches -->"
    ) in output_text
