import sys
from pathlib import Path

import pylhe
import skhep_testdata

from lheutils.cli.lhefix import fix_file


def test_fix_file_preserves_initrwgt_header_when_writing_file(tmp_path, capsys):
    input_file = tmp_path / "input_weighted.lhe"
    output_suffix = ".fixed.lhe"
    input_file.write_text(
        Path("references/files/pylhe-testlhef3.lhe").read_text(),
        encoding="utf-8",
    )

    fix_file(
        filepath=str(input_file),
        compress=False,
        suffix=output_suffix,
        rwgt=False,
        weights=True,
    )

    captured = capsys.readouterr()
    assert "processed" in captured.out

    output_file = input_file.with_name(f"{input_file.stem}{output_suffix}")
    fixed = pylhe.LHEFile.fromfile(output_file)
    assert fixed.header is not None
    assert len(fixed.header.initrwgt.entries) == 1
    entry = fixed.header.initrwgt.entries[0]
    assert isinstance(entry, pylhe.LHEInitRWGTWeightGroup)
    assert entry.attributes["type"] == "scale_variation"
    assert len(entry.weights) == 9


def test_fix_file_preserves_comment_and_root_attributes_on_stdout(
    monkeypatch, capsys
):
    input_file = skhep_testdata.data_path("pylhe-testfile-pr29.lhe")

    with open(input_file, encoding="utf-8") as handle:
        monkeypatch.setattr(sys, "stdin", handle)
        fix_file(None, compress=False, suffix=None, rwgt=True, weights=False)

    output = capsys.readouterr().out
    assert output.startswith('<LesHouchesEvents version="1.0">')
    assert (
        "<!-- File generated by GiBUU. For documentation see "
        "https://gibuu.hepforge.org/trac/wiki/LesHouches -->"
    ) in output
